#!/bin/bash
while getopts i:o:p:Cn optletter
do case $optletter in
i) iflag=1; ival=$OPTARG;;
o) oflag=1; oval=$OPTARG;;
p) pflag=1; pval=$OPTARG;;
C) cflag=1;;
n) nflag=1;;
*) echo Illegal option $optletter
esac
done

if test $cflag
then
coption=-i
fi
if test $nflag
then 
noption=-n
fi
grep $coption $noption $pval $ival > $oval